language: go
sudo: false
go: 1.6

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/stretchr/testify/assert

script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - go build -v ./...
  - go test -v ./...
  - test -z "$(golint ./... |  grep -v 'should have comment' | tee /dev/stderr)"
  - go vet ./...